### ISSUE TITLE
Tests not distributed via Bower

### ISSUE THREAD

**Issue by leegee** [mozilla/localForage-backbone#26]
`bower.json` has `test*` in the `ignore` list — is this intentional? 
I'm trying to get items removed from a collection using the example code from the `README.md`, and would like to see the modify the test and see it pass locally.

**Comment by stephanebachelier** [comment]
@leegee yes it's intentional. Generally only dist are distributed. You will often see that any source or tests folders will be removed, or ignored from bower.

**Comment by stephanebachelier** [comment]
@leegee by the way the release 0.6.0 which is only 4 days old contains a fix to synchronize collection when models are removed. (691c681ea)

**Comment by tofumatt** [comment]
I think it makes sense not to include the tests via bower distribution, because it's presumably folks using it for client-side projects and not working on localforage via a `bower install`. If you wanted to use the tests I'd think using `git` makes more sense... we might even exclude other things from bower.

But I'm for consistency with other projects and the tests aren't big. What do other projects do with their tests and bower?

**Comment by leegee** [comment]
To be fair, most bower installs I've seen exclude the tests.

Please consider my request withdrawn now I've looked around a bit more :)

**Comment by tofumatt** [comment]
No worries, thanks for the update. :smile:
